package(default_visibility = ["//visibility:public"])

java_library(
    name = "uitils-excptions",
    srcs = glob(["**/*.java"]),
    deps = ["@htsjdk//jar",
            "@reflections//jar","@cofoja//jar","@log4j//jar","@commons_io//jar","@colt//jar",
            "@gson//jar","@commons_lang//jar","@freemarker//jar","@fastutil//jar",
            "//lib:javadoc","@httpcomponents//jar"
            ],
)

filegroup(
    name = "excp",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
)
