java_library(
    name = "libsamtools",
    srcs = glob(["**/*.java"]),
    deps = ["//miniutils/src/main/java/htsjdk/lib:htsjdk"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "samtools",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
)


