maven_jar(
    name = "log4j_api",
    artifact = "com.apache.logging.log4j:log4j-api:2.5",
)

maven_jar(
    name = "log4j_core",
    artifact = "com.apache.logging.log4j:log4j-core:2.5",
)

maven_server(
    name = "default",
    url = "http://www.central.maven.org",
)
