package(default_visibility = ["//visibility:public"])

filegroup(
    name = "clib",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
)


#java_library(
#    name = "utils_jna",
#    srcs = glob(["**/*.java"]),
#    deps = ["@jna//jar"],
#    visibility = ["//visibility:public"],
#)

