java_import(
    name = "javadoc",
    jars = ["tools.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "reflections",
    jars = ["reflections-0.9.11-SNAPSHOT.jar"],
    visibility = ["//visibility:public"],
)
